In [1]:
import pandas as pd
import warnings
warnings.filterwarnings ('ignore')

In [2]:
ar=pd.read_csv(r"C:\Users\arjun\Downloads\AmazonFoodReviews.csv")

In [3]:
ar.shape

(568454, 10)

In [12]:
ar.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [13]:
ar.isnull().sum()

Id                         0
ProductId                  0
UserId                     0
ProfileName               26
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

In [10]:
ar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 8 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   UserId                  568454 non-null  object
 1   ProfileName             568428 non-null  object
 2   HelpfulnessNumerator    568454 non-null  int64
 3   HelpfulnessDenominator  568454 non-null  int64
 4   Score                   568454 non-null  int64
 5   Time                    568454 non-null  int64
 6   Summary                 568427 non-null  object
 7   Text                    568454 non-null  object
dtypes: int64(4), object(4)
memory usage: 34.7+ MB

In [20]:
ar.isnull().mean() * 100

Id                        0.000000
ProductId                 0.000000
UserId                    0.000000
ProfileName               0.004574
HelpfulnessNumerator      0.000000
HelpfulnessDenominator    0.000000
Score                     0.000000
Time                      0.000000
Summary                   0.000000
Text                      0.000000
dtype: float64

In [3]:
ar['Summary']=ar['Summary'].fillna('unknown')

In [4]:
ar=ar.drop('ProfileName',axis=1)

In [24]:
ar.head()

,Id,ProductId,UserId,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [5]:
ar=ar.iloc[:,[5,7]]

In [6]:
ar.head(1)

   Score                Summary
0      5  Good Quality Dog Food

In [7]:
ar=ar.rename(columns={'Score':'Y','Summary':'X'})

In [9]:
ar.head(1)

   Y                      X
0  5  Good Quality Dog Food

In [10]:
import nltk

In [11]:
from nltk.corpus import stopwords

In [12]:
l1=stopwords.words('english')
l1

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [13]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [14]:
def text_process(mess):
    """
    1.remove the punctuatiom
    2.remove the stopwords
    3.return the list of clean textwords

    """
    nopunc=[char for char in mess if char not in string.punctuation]
    nopunc="".join(nopunc)
    return [word for word in nopunc.split() if word not in l1]

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
# assign a Id/ token number to each word)

In [16]:
bow_transformer =  CountVectorizer(analyzer = text_process).fit(ar['X'])

In [17]:
len(bow_transformer.vocabulary_)

61300

In [18]:
# tdm -----> term document matrix

In [19]:
tdm = bow_transformer.transform(ar['X'])

In [20]:
tdm.shape

(568454, 61300)

In [21]:
type(tdm)
# tdm will be our X used in model building

scipy.sparse._csr.csr_matrix

In [22]:
ar.Y=ar.Y.replace({1:1,2:1,3:2,4:2,5:2})

In [23]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y,test_y = train_test_split(tdm,ar.Y)

In [24]:
from sklearn.metrics import *

In [25]:
from sklearn.linear_model import LogisticRegression
logrig=LogisticRegression()
logrig.fit(train_x,train_y)
pred = logrig.predict(test_x)
print(confusion_matrix(test_y,pred))
print(classification_report(test_y,pred))

[[ 11270   9405]
 [  3197 118242]]
              precision    recall  f1-score   support

           1       0.78      0.55      0.64     20675
           2       0.93      0.97      0.95    121439

    accuracy                           0.91    142114
   macro avg       0.85      0.76      0.80    142114
weighted avg       0.90      0.91      0.90    142114

In [26]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(train_x, train_y)
pred = dt.predict(test_x)
tab = confusion_matrix(test_y, pred)
print(tab)
print(classification_report(test_y, pred))

[[ 15497   5178]
 [  6190 115249]]
              precision    recall  f1-score   support

           1       0.71      0.75      0.73     20675
           2       0.96      0.95      0.95    121439

    accuracy                           0.92    142114
   macro avg       0.84      0.85      0.84    142114
weighted avg       0.92      0.92      0.92    142114

In [26]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=20,
    class_weight="balanced",
    n_jobs=-1,
    random_state=42
)

rf.fit(train_x, train_y)

pred = rf.predict(test_x)

print(confusion_matrix(test_y, pred))
print(classification_report(test_y, pred))

[[18085  2348]
 [38921 82760]]
              precision    recall  f1-score   support

           1       0.32      0.89      0.47     20433
           2       0.97      0.68      0.80    121681

    accuracy                           0.71    142114
   macro avg       0.64      0.78      0.63    142114
weighted avg       0.88      0.71      0.75    142114